// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type DailyEatingInfo struct {
	UserID             int64
	Date               string
	TotalCalories      int64
	TotalProteins      sql.NullInt64
	TotalFats          sql.NullInt64
	TotalCarbohydrates sql.NullInt64
	DishesIds          string
}

type Dish struct {
	ID            int64
	Name          string
	Calories      int64
	Protein       sql.NullInt64
	Fat           sql.NullInt64
	Carbohydrates sql.NullInt64
	Weight        sql.NullInt64
}
