// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getByUserIDAndDate = `-- name: GetByUserIDAndDate :one
SELECT user_id, date, total_calories, total_proteins, total_fats, total_carbohydrates, dishes_ids
FROM daily_eating_info
WHERE user_id = ?1 AND date = ?2
`

type GetByUserIDAndDateParams struct {
	UserID int64
	Date   string
}

func (q *Queries) GetByUserIDAndDate(ctx context.Context, arg GetByUserIDAndDateParams) (DailyEatingInfo, error) {
	row := q.db.QueryRowContext(ctx, getByUserIDAndDate, arg.UserID, arg.Date)
	var i DailyEatingInfo
	err := row.Scan(
		&i.UserID,
		&i.Date,
		&i.TotalCalories,
		&i.TotalProteins,
		&i.TotalFats,
		&i.TotalCarbohydrates,
		&i.DishesIds,
	)
	return i, err
}

const getDishNameByID = `-- name: GetDishNameByID :one
SELECT id, name, calories, protein, fat, carbohydrates, weight
FROM dishes d
WHERE d.id = ?1
`

func (q *Queries) GetDishNameByID(ctx context.Context, id int64) (Dish, error) {
	row := q.db.QueryRowContext(ctx, getDishNameByID, id)
	var i Dish
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbohydrates,
		&i.Weight,
	)
	return i, err
}

const getGoal = `-- name: GetGoal :one
SELECT user_id, calories, proteins, fats, carbohydrates
FROM user_goals
WHERE user_id = ?1
`

func (q *Queries) GetGoal(ctx context.Context, userID int64) (UserGoal, error) {
	row := q.db.QueryRowContext(ctx, getGoal, userID)
	var i UserGoal
	err := row.Scan(
		&i.UserID,
		&i.Calories,
		&i.Proteins,
		&i.Fats,
		&i.Carbohydrates,
	)
	return i, err
}

const upsertDailyInfo = `-- name: UpsertDailyInfo :exec
INSERT INTO daily_eating_info (user_id, date, total_calories, total_proteins, total_fats, total_carbohydrates, dishes_ids)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
    ON CONFLICT(user_id, date) DO UPDATE SET
    total_calories = EXCLUDED.total_calories,
                                      total_proteins = EXCLUDED.total_proteins,
                                      total_fats = EXCLUDED.total_fats,
                                      total_carbohydrates = EXCLUDED.total_carbohydrates,
                                      dishes_ids = EXCLUDED.dishes_ids
`

type UpsertDailyInfoParams struct {
	UserID             int64
	Date               string
	TotalCalories      int64
	TotalProteins      sql.NullInt64
	TotalFats          sql.NullInt64
	TotalCarbohydrates sql.NullInt64
	DishesIds          string
}

func (q *Queries) UpsertDailyInfo(ctx context.Context, arg UpsertDailyInfoParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyInfo,
		arg.UserID,
		arg.Date,
		arg.TotalCalories,
		arg.TotalProteins,
		arg.TotalFats,
		arg.TotalCarbohydrates,
		arg.DishesIds,
	)
	return err
}

const upsertDishInfo = `-- name: UpsertDishInfo :one
INSERT INTO dishes (name, calories, protein, fat, carbohydrates, weight)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
RETURNING id
`

type UpsertDishInfoParams struct {
	Name          string
	Calories      int64
	Protein       sql.NullInt64
	Fat           sql.NullInt64
	Carbohydrates sql.NullInt64
	Weight        sql.NullInt64
}

func (q *Queries) UpsertDishInfo(ctx context.Context, arg UpsertDishInfoParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertDishInfo,
		arg.Name,
		arg.Calories,
		arg.Protein,
		arg.Fat,
		arg.Carbohydrates,
		arg.Weight,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertGoal = `-- name: UpsertGoal :exec
INSERT INTO user_goals (user_id, calories, proteins, fats, carbohydrates)
VALUES (?1, ?2, ?3, ?4, ?5)
    ON CONFLICT(user_id) DO UPDATE SET
    calories = EXCLUDED.calories,
    proteins = EXCLUDED.proteins,
    fats = EXCLUDED.fats,
    carbohydrates = EXCLUDED.carbohydrates
`

type UpsertGoalParams struct {
	UserID        int64
	Calories      int64
	Proteins      int64
	Fats          int64
	Carbohydrates int64
}

func (q *Queries) UpsertGoal(ctx context.Context, arg UpsertGoalParams) error {
	_, err := q.db.ExecContext(ctx, upsertGoal,
		arg.UserID,
		arg.Calories,
		arg.Proteins,
		arg.Fats,
		arg.Carbohydrates,
	)
	return err
}
